name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@release/v0.1.3
      with:
        channel: '1.19/stable'
        rbac: 'true'
        dns: 'true'
        storage: 'true'
    - name: Test MicroK8s
      id: myactions
      run: |
        kubectl get no
        kubectl get pods -A -o wide
