name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: foo
      run: |
        sudo snap install microk8s --classic
        sudo usermod -a -G microk8s $USER
        sudo chown -f -R $USER ~/.kube
        su - $USER
        microk8s status --wait-ready
        microk8s kubectl get nodes
        microk8s kubectl get services
